[build-system]
requires = ["setuptools >= 68", "wheel","setuptools-git >= 1.1", "pytest-runner", "toml", "reahl-component-metadata >= 7.0.0"]
build-backend = "setuptools.build_meta"

  
[project]
name = "project-b"
version = "4.0"
dependencies = [
  "project-c>=4.0,<4.1",
  "project-a>=4.0,<4.1",
  "reahl-component>=7.0,<7.1"
]

[tool.setuptools.packages.find]
exclude = ["etc", "build", "dist"]

[tool.reahl-component]

[tool.reahl-component.versions.'3.1']
install_requires = [
  "project-c>=3.1,<3.2",
  "project-a>=3.1,<3.2",
  "reahl-component>=7.0,<7.1"
]

[tool.reahl-component.versions.'3.0']
install_requires = [
  "project-c>=3.0,<3.1",
  "project-a>=3.0,<3.1",
  "reahl-component>=7.0,<7.1"
]
